name: Crafting Snapshot Build / 马夫鱼：合成 快照构建

on: [push, pull_request]

jobs:
  snapshot-build-mod:
    runs-on: ubuntu-latest
    steps:
      - name: 获取仓库文件
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: 安装 JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 使用 Gradle 构建
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: 上传 Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mafish-crafting-snapshot-mod
          path: build/libs/*.jar
  
  snapshot-build-datapack:
    runs-on: ubuntu-latest
    steps:
      - name: 获取仓库文件
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
    
      - name: 上传 Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mafish-crafting-snapshot-datapack
          path: |
            src/main/resources/data
            src/main/resources/pack.mcmeta
            src/main/resources/pack.png
